### PR TITLE
Set a type for OSs (bug 1173023)

### PR DESCRIPTION
**Pull request by mstriemer**
This provides more fine-grained detection of a "desktop" for MOW.

### CODE REVIEW

**Comment by chuckharmston** [comment]
r+

**Comment by chuckharmston** [comment]
Actually, maybe take that back—this seems like something we should have tests for.

r+wt

**Comment by mstriemer** [comment]
Good call. I tested with Safari and Chrome's user agent switching for desktop and mobile, respectively. Probably should have copied those strings in instead. Will do so now.

**Comment by mstriemer** [comment]
I added some more tests and everything is still passing.

**Pull request merged**
