### PR TITLE
Use local storage in tests 1137707

### PR DESCRIPTION
**Pull request by mstriemer**
Always use `localStorage` in the `core/user` module.

### CODE REVIEW

**Comment by mstriemer** [comment]
This is included in https://github.com/mozilla/fireplace/pull/1089.

**Comment by mstriemer** [comment]
I'll update the version before I merge this.

**Comment by diox** [comment]
r+

**Comment by ngokevin** [comment]
r+

**Comment by mstriemer** [comment]
:+1: Thanks guys!

**Comment by mstriemer** [comment]
The commit here is https://github.com/mozilla/marketplace-core-modules/commit/46b9289492a4fb895f72d7a7130cd8b7c4ec60b4. I totally messed up merging this...

**Pull request closed without merging**
