### PR TITLE
v1.13.0 clear LS when full (bug 1090567)

### PR DESCRIPTION
**Pull request by ngokevin**

### CODE REVIEW

**Comment by chuckharmston** [comment]
She we refresh after this? Subsequent navigation events might yield unexpected results.

**Comment by chuckharmston** [comment]
r+

**Comment by ngokevin** [comment]
Hmm...that might be a good idea. There are many consequences to continuing on an outdated assumption of what's cached, too many to count.

**Comment by ngokevin** [comment]
Can't really write a test for this atm given karma is coming soon. i'm gonna let this slip in

**Pull request merged**
